services:
  app:
    build:
      context: ./../..
      dockerfile: docker/development/Dockerfile
    container_name: tech-pizza-delivery-waiter-dev
    hostname: tech-pizza-delivery-waiter-dev
    volumes:
      - ./../..:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "${APP_PORT:-80}:80"
