name: Release
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract information from composer.json
        id: composer-info
        run: |
          echo "version=$(jq -r .version composer.json)" >> $GITHUB_OUTPUT
          echo "major=$(echo $(jq -r .version composer.json)" | cut -d'.' -f1)" >> $GITHUB_OUTPUT
          echo "minor=$(echo $(jq -r .version composer.json)" | cut -d'.' -f1).$(echo $(jq -r .version composer.json)" | cut -d'.' -f2)" >> $GITHUB_ENV
          echo "name=$(jq -r .name composer.json)" >> $GITHUB_OUTPUT
          echo "title=$(jq -r .title composer.json)" >> $GITHUB_OUTPUT
          echo "description=$(jq -r .description composer.json)" >> $GITHUB_OUTPUT
          echo "owner=$(jq -r .owner composer.json)" >> $GITHUB_OUTPUT
      - name: Add version Tag
        uses: rickstaa/action-create-tag@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag: ${{ steps.composer-info.outputs.version }}
          tag_exists_error: false
          force_push_tag: true
      - name: Create Release
        uses: actions/create-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.composer-info.outputs.version }}
          release_name: Release ${{ steps.composer-info.outputs.version }}
          prerelease: false
          draft: false
          body: |
            ## Pull Docker Image
            You can pull the release image using the following command:
            ```bash
            $ docker pull ghcr.io/gdgvda/tech-pizza-delivery-waiter:${{ steps.composer-info.outputs.version }}
            ```
      - name: Extract metadata (tags, labels) per Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.version=${{ steps.composer-info.outputs.version }}
            org.opencontainers.image.owner=${{ steps.composer-info.outputs.owner }}
            org.opencontainers.image.title=${{ steps.composer-info.outputs.title }}
            org.opencontainers.image.description=${{ steps.composer-info.outputs.description }}
          tags: |
            type=raw,value=dev,enable=${{ github.event_name == 'pull_request' }}
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=raw,value==${{ steps.composer-info.outputs.version }},enable=${{ steps.composer-info.outputs.version != '' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=raw,value==${{ steps.composer-info.outputs.major }},enable=${{ steps.composer-info.outputs.major != '' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=raw,value==${{ steps.composer-info.outputs.minor }},enable=${{ steps.composer-info.outputs.minor != '' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/production/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
      - name: Delete packages without version
        uses: actions/delete-package-versions@v4
        with:
          package-type: 'container'
          package-name: ${{ github.event.repository.name }}
          delete-only-untagged-versions: true
